### ISSUE TITLE
If behavior method is not defined operation executes successfully 

### ISSUE THREAD

**Issue by litvinovsky** [Freshly/flow#108]
I've just faced with one flow test-case which I think we could improve
basically I've named method behaviors instead of behavior by accident
and my specs were not passing because behaviors was never called

I think we might want to raise error to let developer know that operation does nothing.

**Comment by garside** [comment]
I dun think there's any good intermediary solution here. This sounds to me like tests doing their job and catching the issue!

I tried a quick branch to add like a `raise NotImplementedError` but it felt hokey.
