### ISSUE TITLE
ApplicationOperation is not available in console

### ISSUE THREAD

**Issue by kislak** [Freshly/flow#122]
Readme section for Contributing/Development suggest using ```bin/console``` for experimenting. But most examples are not available from console, because 
``` ApplicationState, ApplicationFlow, ApplicationOperation``` are not defined.

possible fix could be adding the:
```ruby
class ApplicationState < Flow::StateBase; end
class ApplicationFlow < Flow::FlowBase; end
class ApplicationOperation < Flow::OperationBase; end
```

to the ```bin/console``` script.
but it feels like there should be a better alternative.

**Comment by garside** [comment]
Yar, docs kinda assume you have this installed in a rails environment and have run `rails g flow:install` to create these foundational classes.

I'm not opposed to adding them to the bin script! seems innocuous and helpful :)
