### ISSUE TITLE
On states, add `allow_blank: false`

### ISSUE THREAD

**Issue by vinodlala** [Freshly/flow#154]
Instead of:

```
class ReimbursePaymentState < ApplicationState
  argument :amount_cents

  validates :amount_cents, presence: true

  ...
```

It can be:

```
class ReimbursePaymentState < ApplicationState
  argument :amount_cents, allow_blank: false

  ...
```

**Comment by jkminneti** [comment]
Isn't this `allow_nil: false`? Is the ask for an invalid state, rather than an error?

**Comment by jkminneti** [comment]
Either way, oddly enough, this is a question for https://github.com/Freshly/spicerack

**Comment by garside** [comment]
@vinodlala I think this should could just be `allow_nil: false`, but that only checks literal nils. if this is a blank string, there's nothing that will fail that within the state.

**Comment by vinodlala** [comment]
@jkminneti @garside Yes, this is to check for empty strings and return an invalid state.

**Comment by MichelleMik** [comment]
> @jkminneti @garside Yes, this is to check for empty strings and return an invalid state.

Yes, GRPC turns nils into empty strings so it would be useful to have this functionality.

**Comment by arettberg** [comment]
@vinodlala @MichelleMik let's continue this conversation in spicerack, as that's where this feature would be defined

**Comment by arettberg** [comment]
Continued here: https://github.com/Freshly/spicerack/issues/292
