### ISSUE TITLE
One-off Operations

### ISSUE THREAD

**Issue by brandontrumpold** [Freshly/flow#178]
Be able to execute an operation without the need of a flow - simply create a state, then an operation, passing the state into the operation as an arg

**Comment by garside** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/337924/87688415-f502c080-c754-11ea-8b91-c45033ea45d2.png">

Gotta hit ya with the RTFM on this one, unless there's something this doesn't cover?
