### ISSUE TITLE
README syntax error

### ISSUE THREAD

**Issue by EOengineer** [Freshly/flow#211]
The readme has a small syntax error.
`def payment_method
    payment_method.present? payment_method : user.default_payment_method
  end`

This should be 
`def payment_method
    payment_method.present? ? payment_method : user.default_payment_method
  end`

**Comment by EOengineer** [comment]
#212

**Comment by garside** [comment]
@EOengineer heya sorry, we're in the process of moving this repo over to a new organization: https://github.com/RubyAfterAll/flow

This is the new source of the code for this gem - please open the PR against this new location to contribute. Sorry for the confusion / doublework. :(

We'll integrate it eventually if you don't care enough to reopen the work lol.
