### ISSUE TITLE
Attribute defaults for states

### ISSUE THREAD

**Issue by Deorigosa** [Freshly/flow#34]
Allow syntax alike to following:
```ruby
class SomeState < ApplicationState
  argument :whack_a_mole, default: "No fun allowed!"
end
```

Probably involves some keyword argument magic in two places: `argument` method definition and `define_attribute` method definition

**Comment by garside** [comment]
<3

**Comment by garside** [comment]
Gonna call them `outputs` and they're gonna be glorious.
