### ISSUE TITLE
Operation is written to global namespace, should be Flow::Operation

### ISSUE THREAD

**Issue by arettberg** [Freshly/flow#39]

**Comment by garside** [comment]
None of them are namespace actually. They're all just within an unmodulized base:

```ruby
class ApplicationFlow < FlowBase; end 
```

And technically you can use Operations and States without Flows. It's just that Operation isn't as catchy a name for a gem ;)

**Comment by arettberg** [comment]
Sure sure, but let's be clear about how Ruby works. Defining the following module:
```ruby
module Operation
  ...
end
```

means that there is now an object in the global namespace called `Operation`. IMHO, this is unacceptable. A well-written gem writes to exactly one namespace in a predictable manner. This gem makes the assumption (unintentionally, I presume) that no consumer of the gem would ever have another object called `Operation`, which is preposterous. 

_steps off soap box_

**Comment by arettberg** [comment]
I just checked, and we're defining the following *global constants* with this gem:
- `TransactionWrapper`
- `Operation`
- `State`
- `FlowBase`
- `OperationBase`
- `StateBase`
- `Flow`

**Comment by garside** [comment]
Is it all of them?

I really want it to be all of them, because that's significantly less refactoring work.
