### ISSUE TITLE
expect { ... }.to raise_error(OperationFailure.new(x, y)) doesn't work

### ISSUE THREAD

**Issue by arettberg** [Freshly/flow#40]
make a matcher called `raise_operation_failure` or something that does this under the hood:
```ruby
it { is_expected.to raise_error(Operation::Failures::OperationFailure) { |error| expect(error.problem).to eq :stripe_response_no_id } }

**Comment by garside** [comment]
😻

**Comment by garside** [comment]
After some discussion, sounds like this feature might not be necessary in this form, and should be pivoted to be more like:

```ruby
subject { -> { operation.execute } }

it { is_expected.to change { operation.failed? }.from(false).to(true) }
it { is_expected.to change { operation.operation_failure&.problem }.from(nil).to(:problem) }
```

Not sure here. Open to a better suggestion as to what an ideal test case is, but I agree it'd be easier to do this testing with `execute` than the `execute!` approach.

**Comment by garside** [comment]
@arettberg gonna put this on your plate. Can you paste in a snippet of the non-raise based failure testing that you have, and ideally what you want that boilerplate reduced to with the custom matcher?

**Comment by jkminneti** [comment]
The non-raise option really lessens the need for a matcher IMO.

```
subject { operation.operation_failure.problem }

before { operation.execute }

it { is_expected.to eq :some_key }
```

**Comment by garside** [comment]
@jkminneti can you update the `README` with the official suggestion on how to test these?

**Comment by jkminneti** [comment]
#86
