### ISSUE TITLE
_failures is public

### ISSUE THREAD

**Issue by jkminneti** [Freshly/flow#64]
Seems like Operation's `_failures` is supposed to be private or protected, but it's public.

**Comment by garside** [comment]
`_operations` is public on flow as well.

```ruby
module Flow
  module Operations
    extend ActiveSupport::Concern

    included do
      class_attribute :_operations, instance_writer: false, default: []

      delegate :_operations, to: :class
    end
```

I didn't really intend it to be private. We're all consenting adults here. If you need to get at the data, you can publicly access it from the class.

No sense putting a screen door on the submarine, you know?

```ruby
FooOperation.new._failures # => private method error
FooOperations.new.class._failures # => all ur data sir 
```

So I think maybe lets close this? Cause part of me is like "meh" and the other part of me is like `eh` about this lol

**Comment by jkminneti** [comment]
If they're not intended to be private, maybe just remove the underscores?

**Comment by garside** [comment]
Eh. They’re meant to indicate “internal”. Might make sense to make then protected or something instead?

I generally don’t disagree with what you’re getting at, but I’ll pribsblt not get to it fir a bit. I’ll taje a PR that makes me protected tho if you’re feeling impatient. :)

**Comment by garside** [comment]
yea this is like, a thing in Flow. I dunno I can defend it, but it's idiomatic at this point. 

My condolences. :P
