### ISSUE TITLE
Defined reversibility

### ISSUE THREAD

**Issue by jkminneti** [Freshly/flow#65]
When designing a flow or operation that _doesn't_ support rewindability, it'd be nice if there was a way to set that. Otherwise we'll see _a lot_ of this:
```
def undo
  raise NonReversibleError
end
```

It'd be nice if that was handled with a magic class method, with its own custom matcher to boot.

**Comment by garside** [comment]
```ruby
def undo
  irreversible_operation_failure!
end
```

I was considering baking some "default" failures into the operation you could use. Would this get the job done? :)

**Comment by garside** [comment]
At the risk of starting a holy war:

```ruby
class Operation1 < ApplicationOperation
  alias_method :undo, :irreversible_operation_failure!
end
```

🙈

**Comment by garside** [comment]
I mean shit at this point why mince words:

```ruby
class Operation1 < ApplicationOperation

**Comment by jkminneti** [comment]
Yup, that's what I was imagining. Would _potentially_ need the same on Flow though

**Comment by garside** [comment]
eh. I don't see why. A flow should implicitly be reversible if it's operations are... or maybe more idiomatic to say "aren't not", but that makes me feel bad as an english speaker.

I think maybe I'm trying to say if the things don't explicitly forbid being undone, they have a pretty decent expectation they could be? 

I could be shortsighted here, but I'm also really lazy and adding this in one place seems easier/cleaner? :P

**Comment by garside** [comment]
After some conversation, we're just gonna kill it. It's silly.
