### ISSUE TITLE
Prevent nil on arguments

### ISSUE THREAD

**Issue by jkminneti** [Freshly/flow#71]
Currently, nil is allowed as the value for an argument. While that's good default behavior, we may sometimes want to _prevent_ nil. 

I'm envisioning something like this:
```
argument :definitely_need, allow_nil: false
argument :might_need

Flow.new definitely_need: "asdf", might_need: "asdf"
=> good

Flow.new definitely_need: "asdf", might_need: nil
=> also good

Flow.new definitely_need: nil, might_need: nil
=> error!
```
(😄)

For real though, the reasoning is that I'd rather the state tell me it's invalid, than run into NoMethodError's

**Comment by garside** [comment]
👍
