### ISSUE TITLE
failure tests in readme

### ISSUE THREAD

**Issue by mabenson00** [Freshly/flow#76]
Can we add how to test failures to the readme? I'm not sure if this is the correct way - but here's what I have..
`context "when the response is not successful" do
          let(:response) { error_response }

          it "fails with braintree_request" do
            expect{execute.call}.to raise_error(Flow::Operation::Failures::OperationFailure)
            expect(customer).to have_received(:create).with(email: email)
          end
        end
`

**Comment by jkminneti** [comment]
#86
